from django.urls import path
from . import views

app_name = 'mobile_api'

urlpatterns = [
    path('auth/login/', views.api_mobile_login, name='api_mobile_login'),
    path('auth/logout/', views.api_mobile_logout, name='api_mobile_logout'),
    path('card/<int:card_id>/status/', views.api_card_status, name='api_card_status'),
    path('card/<int:card_id>/detail/', views.api_card_detail, name='api_card_detail'),
    path('card/<int:card_id>/delete/', views.api_card_delete, name='api_card_delete'),
    path('table/<int:table_id>/cards/', views.api_cards, name='api_cards'),
    path('table/<int:table_id>/cards/all-ids/', views.api_all_card_ids, name='api_all_card_ids'),
    path('table/<int:table_id>/filter-options/', views.api_filter_options, name='api_filter_options'),
    path('table/<int:table_id>/bulk-status/', views.api_bulk_status, name='api_bulk_status'),
    path('table/<int:table_id>/upload-photo/', views.api_upload_photo, name='api_upload_photo'),
    path('table/<int:table_id>/card/add/', views.api_card_add, name='api_card_add'),
    path('table/<int:table_id>/card/<int:card_id>/update/', views.api_card_update, name='api_card_update'),
    path('table/<int:table_id>/update-fields/', views.api_table_update_fields, name='api_table_update_fields'),
    path('table/<int:table_id>/download-pdf/', views.api_table_download_pdf, name='api_table_download_pdf'),
    path('staff/', views.api_staff_list, name='api_staff_list'),
    path('staff/create/', views.api_staff_create, name='api_staff_create'),
    path('staff/<int:staff_id>/update/', views.api_staff_update, name='api_staff_update'),
    path('staff/<int:staff_id>/toggle/', views.api_staff_toggle, name='api_staff_toggle'),
    path('staff/<int:staff_id>/delete/', views.api_staff_delete, name='api_staff_delete'),
    path('staff/<int:staff_id>/assignable-items/', views.api_staff_assignable_items, name='api_staff_assignable_items'),
    path('staff/<int:staff_id>/assign/', views.api_staff_assign, name='api_staff_assign'),
    path('staff/<int:staff_id>/assignment/', views.api_mobile_staff_assignment, name='api_mobile_staff_assignment'),
    path('staff/<int:staff_id>/assignment/update/', views.api_mobile_staff_assignment_update, name='api_mobile_staff_assignment_update'),
    path('profile/', views.api_profile_data, name='api_profile_data'),
    path('profile/update/', views.api_profile_update, name='api_profile_update'),
    path('profile/change-password/', views.api_profile_change_password, name='api_profile_change_password'),
    path('profile/delete-request/', views.api_profile_delete_request, name='api_profile_delete_request'),
    path('search/', views.api_search, name='api_search'),
    path('server-info/', views.api_server_info, name='api_server_info'),
    path('app-version/', views.api_app_version, name='api_app_version'),
    path('notifications/', views.api_notifications_list, name='api_notifications_list'),
    path('messages/', views.api_messages_list, name='api_messages_list'),
    path('tables/', views.api_tables_list, name='api_tables_list'),
    path('groups/', views.api_groups_list, name='api_groups_list'),
    path('settings/', views.api_settings_data, name='api_settings_data'),
    path('dashboard/', views.api_dashboard_data, name='api_dashboard_data'),
    path('photographer/sync/', views.api_photographer_sync, name='api_photographer_sync'),
    path('photographer/upload-offline/', views.api_photographer_upload_offline, name='api_photographer_upload_offline'),
    path('reprint/<int:client_id>/', views.api_reprint_data, name='api_reprint_data'),
    path('impersonate/users/', views.api_impersonate_users, name='api_impersonate_users'),
    path('impersonate/start/', views.api_impersonate_start, name='api_impersonate_start'),
    path('impersonate/stop/', views.api_impersonate_stop, name='api_impersonate_stop'),
    path('clients/', views.api_clients_list, name='api_clients_list'),
    path('client/create/', views.api_client_create, name='api_client_create'),
    path('client/<int:client_id>/', views.api_client_detail, name='api_client_detail'),
    path('client/<int:client_id>/update/', views.api_client_update, name='api_client_update'),
    path('client/<int:client_id>/toggle/', views.api_client_toggle, name='api_client_toggle'),
    path('client/<int:client_id>/delete/', views.api_client_delete, name='api_client_delete'),
    path('client/<int:client_id>/tables/', views.api_client_tables, name='api_client_tables'),
    path('client/<int:client_id>/groups/', views.api_client_groups_detail, name='api_client_groups_detail'),
    path('client/<int:client_id>/group/create/', views.api_group_create, name='api_group_create'),
    path('group/<int:group_id>/update/', views.api_group_update, name='api_group_update'),
    path('group/<int:group_id>/delete/', views.api_group_delete, name='api_group_delete'),
    path('group/<int:group_id>/table/create/', views.api_table_create, name='api_table_create'),
    path('table/<int:table_id>/rename/', views.api_table_rename, name='api_table_rename'),
    path('table/<int:table_id>/delete/', views.api_table_delete, name='api_table_delete'),
    path('table/<int:table_id>/fields/', views.api_table_fields_get, name='api_table_fields_get'),
    
    # Public Website Fallbacks (since website app was removed)
    path('pub/website/landing/', views.api_website_landing_data, name='api_website_landing_data'),
    path('pub/website/contact/', views.api_website_contact_submit, name='api_website_contact_submit'),
    path('website/portfolio/upload/', views.api_website_portfolio_upload, name='api_website_portfolio_upload'),
    path('website/portfolio/category/<int:category_id>/items/', views.api_website_portfolio_category_items, name='api_website_portfolio_category_items'),

    # Device token registration for push notifications
    path('device-token/register/', views.api_register_device_token, name='api_register_device_token'),
    path('validate-photo/', views.api_validate_photo, name='api_validate_photo'),
]
