# Generated by Django 5.2.12 on 2026-04-25 07:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('device_type', models.CharField(choices=[('web', 'Web Browser'), ('mobile', 'Mobile App/Phone')], max_length=10)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Device Session',
                'verbose_name_plural': 'User Device Sessions',
                'indexes': [models.Index(fields=['user', 'device_type'], name='accounts_us_user_id_931c37_idx'), models.Index(fields=['last_active'], name='accounts_us_last_ac_acb9bf_idx')],
            },
        ),
    ]
