# Generated by Django 5.2.12 on 2026-08-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0006_initial_domain_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmedia',
            name='field_name',
            field=models.CharField(blank=True, help_text='Dynamic field name from Table (e.g., "Photo", "Father Photo")', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cardmedia',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Associated Table (for template images)', null=True, on_delete=models.deletion.CASCADE, related_name='template_media_files', to='tables.table'),
        ),
    ]
