# Generated by Django 5.2.12 on 2026-08-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_alter_idcard_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(default='organisation', help_text='primary, organisation, or manager', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='is_default',
            field=models.BooleanField(default=False, help_text='System default organisation'),
        ),
    ]
