# Generated by Django 5.2.12 on 2026-08-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_rename_staff_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target',
            field=models.CharField(choices=[('all', 'All Users'), ('super_admin', 'Super Admins'), ('operator', 'Admin Staff / Operators'), ('prime_manager', 'Prime Managers'), ('manager', 'Managers'), ('assistant', 'Assistants'), ('selected', 'Selected Users')], default='all', max_length=20),
        ),
    ]
