# Generated by Django 5.2.12 on 2026-08-17 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0113_organisation_max_super_managers_alter_user_role'),
        ('tables', '0004_tableaccess_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, default='', help_text='Session or device identifier for guest/tab scoping', max_length=100)),
                ('operation_type', models.CharField(choices=[('card_update', 'Single Card Edit'), ('card_create', 'Create Card'), ('card_delete', 'Delete Card'), ('card_restore', 'Restore Card'), ('bulk_update', 'Bulk Card Update'), ('bulk_status', 'Bulk Status Change'), ('bulk_delete', 'Bulk Delete'), ('bulk_restore', 'Bulk Restore'), ('media_update', 'Media Upload / Replace'), ('crop_update', 'Crop Metadata Change'), ('import_data', 'Data Ingestion Import'), ('move_cards', 'Move Cards'), ('undo_operation', 'Undo Operation'), ('redo_operation', 'Redo Operation'), ('custom', 'Custom Action')], db_index=True, default='card_update', max_length=50)),
                ('target_type', models.CharField(db_index=True, default='card', help_text='Primary entity type: card, table, media, batch, import', max_length=50)),
                ('description', models.CharField(help_text='Human-readable summary, e.g. "Changed status for 24 cards"', max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('undone', 'Undone'), ('partially_undone', 'Partially Undone'), ('conflicted', 'Conflicted'), ('redone', 'Redone'), ('failed', 'Failed')], db_index=True, default='active', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary operation metadata (job IDs, batch counts, crop boxes)')),
                ('schema_version', models.PositiveIntegerField(default=1, help_text='Payload schema version for long-term backward compatibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='core.organisation')),
                ('parent_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_operations', to='operations.operation')),
                ('redo_of', models.ForeignKey(blank=True, help_text='The undone operation that this redo event reapplied', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redone_by', to='operations.operation')),
                ('target_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='tables.table')),
                ('undo_of', models.ForeignKey(blank=True, help_text='The original operation that this undo event reversed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undone_by', to='operations.operation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_operation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.IntegerField(db_index=True, help_text='Target entity PK (e.g. card_id, table_id)')),
                ('target_model', models.CharField(db_index=True, default='idcard', max_length=50)),
                ('field_name', models.CharField(db_index=True, help_text='Dynamic field name (e.g. "NAME", "CLASS", "STATUS", "PHOTO")', max_length=100)),
                ('change_type', models.CharField(choices=[('field_edit', 'Field Edit'), ('status_change', 'Status Change'), ('record_create', 'Record Create'), ('record_delete', 'Record Delete'), ('record_restore', 'Record Restore'), ('media_replace', 'Media Replace'), ('crop_change', 'Crop Change')], db_index=True, default='field_edit', max_length=50)),
                ('before_value', models.JSONField(blank=True, help_text='Exact state before operation (preserves types, null vs empty)', null=True)),
                ('after_value', models.JSONField(blank=True, help_text='Exact state after operation', null=True)),
                ('expected_version', models.PositiveIntegerField(default=1, help_text='Optimistic concurrency version tag')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('undone', 'Undone'), ('conflicted', 'Conflicted'), ('skipped', 'Skipped')], db_index=True, default='applied', max_length=30)),
                ('conflict_reason', models.CharField(blank=True, default='', help_text='Reason if rollback encountered a multi-user conflict', max_length=255)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='operations.operation')),
            ],
            options={
                'db_table': 'core_operationchange',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['organisation', 'status'], name='core_operat_organis_3dcaa5_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['target_table', 'status'], name='core_operat_target__a1b91d_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['user', 'status', 'created_at'], name='core_operat_user_id_6c0fb4_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['organisation', 'user', 'target_table', 'status'], name='core_operat_organis_e8111f_idx'),
        ),
        migrations.AddIndex(
            model_name='operationchange',
            index=models.Index(fields=['operation', 'target_id'], name='core_operat_operati_c6d8df_idx'),
        ),
        migrations.AddIndex(
            model_name='operationchange',
            index=models.Index(fields=['target_model', 'target_id'], name='core_operat_target__5a73dc_idx'),
        ),
        migrations.AddIndex(
            model_name='operationchange',
            index=models.Index(fields=['target_model', 'target_id', 'field_name'], name='core_operat_target__9f0101_idx'),
        ),
    ]
