# Generated by Django 5.2.12 on 2026-08-17 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_organisation_max_super_managers_alter_user_role'),
        ('operations', '0001_initial'),
        ('tables', '0004_tableaccess_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_code', models.CharField(db_index=True, help_text='Human-readable transaction reference, e.g. "BT-20260817-001"', max_length=64, unique=True)),
                ('actor_name_snapshot', models.CharField(blank=True, default='', help_text='Display name snapshot at the time of transaction', max_length=150)),
                ('actor_role_snapshot', models.CharField(blank=True, default='', help_text='Role snapshot at the time of transaction (e.g. assistant, super_manager)', max_length=50)),
                ('actor_type', models.CharField(choices=[('user', 'User'), ('system', 'System'), ('api', 'API Client'), ('worker', 'Background Worker'), ('ai', 'AI Engine'), ('import', 'Import Worker'), ('operator', 'Operator')], default='user', max_length=30)),
                ('action', models.CharField(choices=[('bulk_status', 'Bulk Status Change'), ('bulk_update', 'Bulk Card Update'), ('bulk_delete', 'Bulk Delete'), ('bulk_restore', 'Bulk Restore'), ('import_data', 'Data Ingestion Import'), ('export_data', 'Data Export'), ('media_reupload', 'Bulk Media Reupload'), ('reverse_transaction', 'Reverse Transaction')], db_index=True, default='bulk_status', max_length=50)),
                ('source_state', models.CharField(blank=True, default='', help_text='Initial status/state before transaction (e.g. "pending")', max_length=50)),
                ('destination_state', models.CharField(blank=True, default='', help_text='Target status/state after transaction (e.g. "verified")', max_length=50)),
                ('requested_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('conflict_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('visibility_scope', models.CharField(choices=[('ORGANISATION', 'Organisation (Visible to Client & Staff)'), ('INTERNAL_ADMIN', 'Internal Admin (Operators & Staff)'), ('PRIME_ADMIN', 'Prime Admin Only'), ('SUPER_ADMIN', 'Super Admin Only'), ('SYSTEM', 'System Internal')], db_index=True, default='ORGANISATION', max_length=30)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('partially_completed', 'Partially Completed'), ('reversed', 'Reversed'), ('partially_reversed', 'Partially Reversed'), ('failed', 'Failed')], db_index=True, default='completed', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Supplementary transaction parameters, job IDs, IP address, device')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_transactions', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_transactions', to='core.organisation')),
                ('reversed_by_transaction', models.ForeignKey(blank=True, help_text='New transaction that reversed this historical transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverses_transaction', to='operations.bulktransaction')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_transactions', to='tables.table')),
            ],
            options={
                'db_table': 'core_bulktransaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, help_text='Unique event identity string, e.g. "EVT-20260817-001234"', max_length=64, unique=True)),
                ('actor_name_snapshot', models.CharField(blank=True, default='', help_text='Display name at time of event', max_length=150)),
                ('actor_role_snapshot', models.CharField(blank=True, default='', help_text='Role at time of event (assistant, super_manager, prime_admin, etc.)', max_length=50)),
                ('actor_type', models.CharField(default='user', help_text='user, system, api, worker, ai, import', max_length=30)),
                ('event_type', models.CharField(choices=[('create', 'Record Created'), ('update', 'Record Updated'), ('delete', 'Record Deleted'), ('restore', 'Record Restored'), ('status_change', 'Status Changed'), ('move', 'Record Moved'), ('approve', 'Approved'), ('verify', 'Verified'), ('unverify', 'Unverified'), ('reject', 'Rejected'), ('media_upload', 'Media Uploaded'), ('media_replace', 'Media Replaced'), ('media_delete', 'Media Removed'), ('crop_update', 'Crop Box Updated'), ('bulk_status', 'Bulk Status Applied'), ('bulk_update', 'Bulk Field Update'), ('import_data', 'Data Ingestion Import'), ('export_data', 'Data Export'), ('schema_change', 'Schema Modified'), ('user_action', 'User / Role Mutation'), ('system_action', 'System Action')], db_index=True, default='update', max_length=50)),
                ('target_type', models.CharField(choices=[('card', 'ID Card'), ('table', 'Table'), ('field', 'Dynamic Field'), ('media', 'Media File'), ('user', 'User / Account'), ('organisation', 'Organisation'), ('import', 'Import Job'), ('export', 'Export Job'), ('bulk_transaction', 'Bulk Transaction')], db_index=True, default='card', max_length=50)),
                ('target_id', models.IntegerField(db_index=True, help_text='Target entity PK (card_id, table_id, etc.)')),
                ('target_name_snapshot', models.CharField(blank=True, default='', help_text='Target entity label snapshot (e.g. "Rahul Sharma (Card #1023)")', max_length=255)),
                ('field_deltas', models.JSONField(blank=True, default=list, help_text='Granular field-level changes: [{field_id, field_name, before_value, after_value, change_type}]')),
                ('visibility_scope', models.CharField(choices=[('ORGANISATION', 'Organisation'), ('INTERNAL_ADMIN', 'Internal Admin'), ('PRIME_ADMIN', 'Prime Admin'), ('SUPER_ADMIN', 'Super Admin'), ('SYSTEM', 'System')], db_index=True, default='ORGANISATION', max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, default='', max_length=100)),
                ('source', models.CharField(default='web_panel', help_text='Origin client: web_panel, mobile_app, desktop_app, api, worker', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='operations.operation')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='core.organisation')),
                ('target_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='tables.table')),
                ('bulk_transaction', models.ForeignKey(blank=True, help_text='Parent bulk transaction if event was part of a mass operation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='operations.bulktransaction')),
            ],
            options={
                'db_table': 'core_auditevent',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bulktransaction',
            index=models.Index(fields=['organisation', 'created_at'], name='core_bulktr_organis_d4686b_idx'),
        ),
        migrations.AddIndex(
            model_name='bulktransaction',
            index=models.Index(fields=['table', 'created_at'], name='core_bulktr_table_i_e41d47_idx'),
        ),
        migrations.AddIndex(
            model_name='bulktransaction',
            index=models.Index(fields=['organisation', 'visibility_scope', 'created_at'], name='core_bulktr_organis_8a5707_idx'),
        ),
        migrations.AddIndex(
            model_name='bulktransaction',
            index=models.Index(fields=['actor', 'created_at'], name='core_bulktr_actor_i_bd673b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['organisation', 'created_at'], name='core_audite_organis_2a4f39_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['target_type', 'target_id', 'created_at'], name='core_audite_target__c48222_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['target_table', 'created_at'], name='core_audite_target__a1ac92_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['actor', 'created_at'], name='core_audite_actor_i_5b4f87_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['organisation', 'visibility_scope', 'created_at'], name='core_audite_organis_843fab_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['bulk_transaction', 'created_at'], name='core_audite_bulk_tr_be5ce5_idx'),
        ),
    ]
