# Generated by Django 5.2.12 on 2026-08-12 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0003_assistant_org_fk_and_tables_m2m'),
        ('core', '0109_alter_organisation_org_type_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='assistant',
                    name='organisation',
                    field=models.ForeignKey(blank=True, db_column='client_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='core.organisation'),
                ),
                migrations.AlterField(
                    model_name='assistant',
                    name='perm_manage_assistants',
                    field=models.BooleanField(db_column='perm_manage_client_staff', default=False),
                ),
                migrations.AlterField(
                    model_name='assistant',
                    name='perm_organisation_list',
                    field=models.BooleanField(db_column='perm_idcard_client_list', default=False),
                ),
            ],
            database_operations=[]
        )
    ]
