# Generated by Django 5.2.12 on 2026-08-12 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial_domain_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
