# Generated by Django 5.2.12 on 2026-08-12 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial_domain_models'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name='idcard',
                    new_name='core_idcard_table_i_85127c_idx',
                    old_name='tables_idca_table_i_6bbdc1_idx',
                ),
                migrations.RenameIndex(
                    model_name='idcard',
                    new_name='core_idcard_status_a9d94a_idx',
                    old_name='tables_idca_status_cd73b4_idx',
                ),
                migrations.RenameIndex(
                    model_name='idcard',
                    new_name='core_idcard_table_i_a6fa6f_idx',
                    old_name='tables_idca_table_i_6d11fc_idx',
                ),
                migrations.RenameIndex(
                    model_name='idcard',
                    new_name='core_idcard_created_ff3f57_idx',
                    old_name='tables_idca_created_ddc17c_idx',
                ),
                migrations.RenameIndex(
                    model_name='idcard',
                    new_name='core_idcard_updated_8223db_idx',
                    old_name='tables_idca_updated_edebe9_idx',
                ),
                migrations.RenameIndex(
                    model_name='table',
                    new_name='core_idcard_organis_65641d_idx',
                    old_name='tables_tabl_organis_45808b_idx',
                ),
                migrations.RenameIndex(
                    model_name='table',
                    new_name='core_idcard_is_acti_774067_idx',
                    old_name='tables_tabl_is_acti_52d2fd_idx',
                ),
                migrations.RenameIndex(
                    model_name='table',
                    new_name='core_idcard_created_100402_idx',
                    old_name='tables_tabl_created_b2274c_idx',
                ),
                migrations.AlterModelTable(
                    name='idcard',
                    table='core_idcard',
                ),
                migrations.AlterModelTable(
                    name='table',
                    table='core_idcardtable',
                ),
            ],
            database_operations=[]
        )
    ]
