# Generated by Django 5.2.10 on 2026-02-06 12:25

import django.db.models.deletion
import mediafiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_add_assigned_clients_to_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(help_text='The actual image file', upload_to=mediafiles.models.card_media_upload_path)),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('mother_photo', 'Mother Photo'), ('father_photo', 'Father Photo'), ('barcode', 'Barcode'), ('qr_code', 'QR Code'), ('signature', 'Signature'), ('template_front', 'Template Front'), ('template_back', 'Template Back'), ('other', 'Other')], db_index=True, default='photo', help_text='Type/role of this media file', max_length=20)),
                ('original_filename', models.CharField(blank=True, db_index=True, help_text='Original filename from upload/Excel for matching', max_length=255, null=True)),
                ('field_name', models.CharField(blank=True, help_text='Dynamic field name from IDCardTable (e.g., "Photo", "Father Photo")', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_migrated', models.BooleanField(default=False, help_text='True if migrated from legacy storage (field_data/ImageField)')),
                ('legacy_path', models.CharField(blank=True, help_text='Original path in legacy storage (for reference/rollback)', max_length=500, null=True)),
                ('card', models.ForeignKey(blank=True, help_text='Associated ID card (null for template images)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='core.idcard')),
                ('client', models.ForeignKey(help_text='Client owner for data scoping', on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='core.client')),
                ('group', models.ForeignKey(blank=True, help_text='Associated ID card group (for template images)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='core.idcardgroup')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded this file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Card Media',
                'verbose_name_plural': 'Card Media',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'media_type'], name='mediafiles__client__a8c24a_idx'), models.Index(fields=['card', 'media_type'], name='mediafiles__card_id_696b76_idx'), models.Index(fields=['original_filename'], name='mediafiles__origina_44dbc7_idx')],
            },
        ),
    ]
