# Generated by Django 5.2.10 on 2026-02-14 11:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_production_indexes'),
        ('mediafiles', '0001_create_cardmedia_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cardmedia',
            index=models.Index(fields=['card', 'field_name'], name='mediafiles__card_id_2a384a_idx'),
        ),
        migrations.AddIndex(
            model_name='cardmedia',
            index=models.Index(fields=['created_at'], name='mediafiles__created_761131_idx'),
        ),
    ]
