# Generated by Django 5.2.10 on 2026-03-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0002_production_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cardmedia',
            index=models.Index(fields=['file'], name='mediafiles__file_dbc7f5_idx'),
        ),
    ]
