# Generated by Django 5.2.12 on 2026-04-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0003_cardmedia_file_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmedia',
            name='media_type',
            field=models.CharField(choices=[('photo', 'Photo'), ('rel_photo', 'Relation Photo'), ('mother_photo', 'Mother Photo (Legacy)'), ('father_photo', 'Father Photo (Legacy)'), ('barcode', 'Barcode'), ('qr_code', 'QR Code'), ('signature', 'Signature'), ('template_front', 'Template Front'), ('template_back', 'Template Back'), ('other', 'Other')], db_index=True, default='photo', help_text='Type/role of this media file', max_length=20),
        ),
    ]
