# Generated by Django 5.2.12 on 2026-07-27 10:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_photographer_perm_mobile_app_default_true'),
        ('mediafiles', '0004_alter_cardmedia_media_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmedia',
            name='last_edited_by_role',
            field=models.CharField(choices=[('a', 'Admin'), ('c', 'Client'), ('o', 'Operator')], default='a', help_text='Role of the last uploader/editor', max_length=1),
        ),
        migrations.AddField(
            model_name='cardmedia',
            name='root_token',
            field=models.CharField(blank=True, db_index=True, help_text='14-digit root token (HHMMSSmmmuuuCC) created on 1st upload', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cardmedia',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('undo_stack', 'Undo Stack'), ('redo_stack', 'Redo Stack'), ('expired', 'Expired')], db_index=True, default='active', help_text='History status of this media version', max_length=20),
        ),
        migrations.AddField(
            model_name='cardmedia',
            name='version',
            field=models.IntegerField(default=0, help_text='Incrementing version number (0 for initial upload, 1, 2, 3...)'),
        ),
        migrations.AddIndex(
            model_name='cardmedia',
            index=models.Index(fields=['card', 'field_name', 'status'], name='mediafiles__card_id_ef56cd_idx'),
        ),
        migrations.AddIndex(
            model_name='cardmedia',
            index=models.Index(fields=['root_token', 'version'], name='mediafiles__root_to_a980aa_idx'),
        ),
        migrations.AddIndex(
            model_name='cardmedia',
            index=models.Index(fields=['created_at', 'status'], name='mediafiles__created_a9da05_idx'),
        ),
    ]
