# Generated by Django 5.2.12 on 2026-08-12 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_initial_domain_models'),
        ('mediafiles', '0005_cardmedia_last_edited_by_role_cardmedia_root_token_and_more'),
        ('tables', '0001_initial_domain_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmedia',
            name='card',
            field=models.ForeignKey(blank=True, help_text='Associated ID card (null for template images)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='tables.idcard'),
        ),
        migrations.AlterField(
            model_name='cardmedia',
            name='client',
            field=models.ForeignKey(help_text='Organisation owner for data scoping', on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='core.organisation'),
        ),
        migrations.AlterField(
            model_name='cardmedia',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Associated Table (for template images)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_media_files', to='tables.table'),
        ),
    ]
