# Generated by Django 5.2.12 on 2026-08-12 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0103_initial_domain_models'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Table',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(db_index=True, max_length=255)),
                        ('description', models.TextField(blank=True, null=True)),
                        ('table_type', models.CharField(choices=[('school_student', 'School Student'), ('college_student', 'College Student'), ('staff', 'Staff / Employee'), ('custom', 'Custom')], default='custom', help_text='Auto-detected from table name and organisation type.', max_length=20)),
                        ('fields', models.JSONField(default=list, help_text='List of field configurations: [{name, type, order}]. Max 20 fields.')),
                        ('is_active', models.BooleanField(default=True)),
                        ('deleted_by_manager', models.BooleanField(default=False, help_text='True when the prime manager soft-deletes this table.')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='core.organisation')),
                    ],
                    options={
                        'db_table': 'core_idcardtable',
                        'ordering': ['-created_at'],
                    },
                ),
                migrations.CreateModel(
                    name='IDCard',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('field_data', models.JSONField(default=dict, help_text='Dynamic field values based on table fields.')),
                        ('photo', models.ImageField(blank=True, help_text='DEPRECATED: Use CardMedia model for new photos', null=True, upload_to='id_photos/')),
                        ('original_photo_name', models.CharField(blank=True, db_index=True, help_text='Original photo name from Excel for matching', max_length=255, null=True)),
                        ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('approved', 'Approved'), ('printed', 'Printed'), ('request', 'Requested'), ('deleted', 'Deleted'), ('download', 'Downloaded'), ('pool', 'In Pool'), ('reprint', 'Reprint')], db_index=True, default='pending', max_length=20)),
                        ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                        ('deleted_at', models.DateTimeField(blank=True, null=True)),
                        ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                        ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to='tables.table')),
                    ],
                    options={
                        'db_table': 'core_idcard',
                        'ordering': ['-created_at'],
                    },
                ),
                migrations.AddIndex(
                    model_name='table',
                    index=models.Index(fields=['organisation', 'is_active'], name='tables_tabl_organis_45808b_idx'),
                ),
                migrations.AddIndex(
                    model_name='table',
                    index=models.Index(fields=['is_active'], name='tables_tabl_is_acti_52d2fd_idx'),
                ),
                migrations.AddIndex(
                    model_name='table',
                    index=models.Index(fields=['created_at'], name='tables_tabl_created_b2274c_idx'),
                ),
                migrations.AddIndex(
                    model_name='idcard',
                    index=models.Index(fields=['table', 'status'], name='tables_idca_table_i_6bbdc1_idx'),
                ),
                migrations.AddIndex(
                    model_name='idcard',
                    index=models.Index(fields=['status', 'created_at'], name='tables_idca_status_cd73b4_idx'),
                ),
                migrations.AddIndex(
                    model_name='idcard',
                    index=models.Index(fields=['table', 'created_at'], name='tables_idca_table_i_6d11fc_idx'),
                ),
                migrations.AddIndex(
                    model_name='idcard',
                    index=models.Index(fields=['created_at'], name='tables_idca_created_ddc17c_idx'),
                ),
                migrations.AddIndex(
                    model_name='idcard',
                    index=models.Index(fields=['updated_at'], name='tables_idca_updated_edebe9_idx'),
                ),
                migrations.AddIndex(
                    model_name='idcard',
                    index=models.Index(fields=['table', 'status', '-id'], name='tbl_status_id_desc'),
                ),
                migrations.AddIndex(
                    model_name='idcard',
                    index=models.Index(fields=['table', 'status', '-status_changed_at', '-id'], name='tbl_st_chg_id_idx'),
                ),
                migrations.AddIndex(
                    model_name='idcard',
                    index=models.Index(fields=['table', 'status', '-downloaded_at', '-id'], name='tbl_st_dld_id_idx'),
                ),
                migrations.AddIndex(
                    model_name='idcard',
                    index=models.Index(fields=['table', 'status', '-deleted_at', '-id'], name='tbl_st_del_id_idx'),
                ),
                migrations.AddIndex(
                    model_name='idcard',
                    index=models.Index(fields=['downloaded_at'], name='tbl_downloaded_at_idx'),
                ),
                migrations.AddIndex(
                    model_name='idcard',
                    index=models.Index(fields=['deleted_at'], name='tbl_deleted_at_idx'),
                ),
                migrations.AddIndex(
                    model_name='idcard',
                    index=models.Index(fields=['status_changed_at'], name='tbl_status_changed_at_idx'),
                ),
            ],
            database_operations=[],
        ),
    ]
