# Generated by Django 5.2.12 on 2026-08-15 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_add_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True)),
                ('can_edit_cards', models.BooleanField(default=True)),
                ('can_approve_print', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_accesses', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_accesses', to='tables.table')),
            ],
            options={
                'db_table': 'tables_tableaccess',
            },
        ),
        migrations.AddConstraint(
            model_name='tableaccess',
            constraint=models.UniqueConstraint(fields=('table', 'manager'), name='unique_table_manager_access'),
        ),
    ]
