# Generated by Django 5.2.7 on 2026-08-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_tableaccess_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name='table',
                    new_name='core_idcard_client__2687fe_idx',
                    old_name='core_idcard_organis_65641d_idx',
                ),
                migrations.AlterField(
                    model_name='table',
                    name='deleted_by_manager',
                    field=models.BooleanField(db_column='deleted_by_client', default=False, help_text='True when the prime manager soft-deletes this table.'),
                ),
            ],
            database_operations=[],
        ),
    ]
