# Generated by Django 5.2.12 on 2026-06-28 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0090_alter_user_role_photographer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('perm_idcard_client_list', models.BooleanField(default=False)),
                ('perm_manage_client_staff', models.BooleanField(default=False)),
                ('perm_idcard_setting_list', models.BooleanField(default=False)),
                ('perm_idcard_setting_add', models.BooleanField(default=False)),
                ('perm_idcard_setting_edit', models.BooleanField(default=False)),
                ('perm_idcard_setting_delete', models.BooleanField(default=False)),
                ('perm_idcard_setting_status', models.BooleanField(default=False)),
                ('perm_idcard_pending_list', models.BooleanField(default=False)),
                ('perm_idcard_verified_list', models.BooleanField(default=False)),
                ('perm_idcard_pool_list', models.BooleanField(default=False)),
                ('perm_idcard_approved_list', models.BooleanField(default=False)),
                ('perm_idcard_download_list', models.BooleanField(default=False)),
                ('perm_idcard_reprint_list', models.BooleanField(default=False)),
                ('perm_reprint_request_list', models.BooleanField(default=False)),
                ('perm_confirmed_list', models.BooleanField(default=False)),
                ('perm_idcard_add', models.BooleanField(default=False)),
                ('perm_idcard_edit', models.BooleanField(default=False)),
                ('perm_idcard_delete', models.BooleanField(default=False)),
                ('perm_idcard_info', models.BooleanField(default=False)),
                ('perm_idcard_approve', models.BooleanField(default=False)),
                ('perm_idcard_verify', models.BooleanField(default=False)),
                ('perm_idcard_updated_at', models.BooleanField(default=False)),
                ('perm_idcard_delete_from_pool', models.BooleanField(default=False)),
                ('perm_idcard_clear_pending_path', models.BooleanField(default=False)),
                ('perm_reupload_idcard_image', models.BooleanField(default=False)),
                ('perm_idcard_retrieve', models.BooleanField(default=False)),
                ('perm_idcard_bulk_upload', models.BooleanField(default=False)),
                ('perm_idcard_bulk_download', models.BooleanField(default=False)),
                ('perm_idcard_download_image_rename_mode', models.BooleanField(default=False)),
                ('perm_idcard_download_image_generate_mode', models.BooleanField(default=False)),
                ('perm_idcard_bulk_reupload', models.BooleanField(default=False)),
                ('perm_idcard_upgrade_all', models.BooleanField(default=False)),
                ('perm_mobile_app', models.BooleanField(default=False)),
                ('perm_manage_panel_backup', models.BooleanField(default=False)),
                ('perm_manage_panel_email', models.BooleanField(default=False)),
                ('perm_pro_user_options', models.BooleanField(default=False)),
                ('perm_pro_log_deletion_guard', models.BooleanField(default=False)),
                ('perm_pro_data_deletion_guard', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_clients', models.ManyToManyField(blank=True, related_name='assigned_operators', to='core.client')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
