# Generated by Django 5.2.12 on 2026-06-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='perm_manage_photographer_staff',
            field=models.BooleanField(default=False),
        ),
    ]
