# Generated by Django 5.2.12 on 2026-08-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_initial_domain_models'),
        ('operators', '0002_operator_perm_manage_photographer_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='assigned_clients',
            field=models.ManyToManyField(blank=True, related_name='assigned_operators', to='core.organisation'),
        ),
    ]
