# Generated by Django 5.2.12 on 2026-08-12 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0003_initial_domain_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operator',
            old_name='assigned_clients',
            new_name='assigned_organisations',
        ),
        migrations.RenameField(
            model_name='operator',
            old_name='perm_manage_client_staff',
            new_name='perm_manage_assistant',
        ),
    ]
