# Generated by Django 5.2.12 on 2026-08-15 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0113_organisation_max_super_managers_alter_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_type', models.CharField(choices=[('prime_manager', 'Prime Manager'), ('super_manager', 'Super Manager'), ('guest_manager', 'Guest Manager')], db_index=True, default='super_manager', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('perm_organisation_list', models.BooleanField(default=False)),
                ('perm_manage_assistants', models.BooleanField(default=True)),
                ('perm_idcard_setting_list', models.BooleanField(default=True)),
                ('perm_idcard_setting_add', models.BooleanField(default=False)),
                ('perm_idcard_setting_edit', models.BooleanField(default=True)),
                ('perm_idcard_setting_delete', models.BooleanField(default=False)),
                ('perm_idcard_setting_status', models.BooleanField(default=True)),
                ('perm_idcard_pending_list', models.BooleanField(default=True)),
                ('perm_idcard_verified_list', models.BooleanField(default=True)),
                ('perm_idcard_pool_list', models.BooleanField(default=True)),
                ('perm_idcard_approved_list', models.BooleanField(default=True)),
                ('perm_idcard_download_list', models.BooleanField(default=True)),
                ('perm_idcard_reprint_list', models.BooleanField(default=True)),
                ('perm_reprint_request_list', models.BooleanField(default=True)),
                ('perm_confirmed_list', models.BooleanField(default=True)),
                ('perm_idcard_add', models.BooleanField(default=True)),
                ('perm_idcard_edit', models.BooleanField(default=True)),
                ('perm_idcard_delete', models.BooleanField(default=True)),
                ('perm_idcard_info', models.BooleanField(default=True)),
                ('perm_idcard_approve', models.BooleanField(default=True)),
                ('perm_idcard_verify', models.BooleanField(default=True)),
                ('perm_idcard_updated_at', models.BooleanField(default=True)),
                ('perm_idcard_delete_from_pool', models.BooleanField(default=False)),
                ('perm_reupload_idcard_image', models.BooleanField(default=True)),
                ('perm_idcard_retrieve', models.BooleanField(default=True)),
                ('perm_idcard_bulk_upload', models.BooleanField(default=True)),
                ('perm_idcard_bulk_download', models.BooleanField(default=True)),
                ('perm_idcard_download_image_rename_mode', models.BooleanField(default=True)),
                ('perm_idcard_download_image_generate_mode', models.BooleanField(default=True)),
                ('perm_idcard_bulk_reupload', models.BooleanField(default=False)),
                ('perm_delete_all_idcard', models.BooleanField(default=False)),
                ('perm_idcard_upgrade_all', models.BooleanField(default=False)),
                ('perm_mobile_app', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='core.organisation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org_manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organisation_manager',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organisation', 'manager_type'], name='organisatio_client__ee1bb9_idx'), models.Index(fields=['manager_type', 'is_active'], name='organisatio_manager_4ca438_idx')],
            },
        ),
    ]
