# Generated by Django 5.2.10 on 2026-02-05 02:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Adarsh ID Cards', max_length=200)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('site_favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('about_text', models.TextField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Settings',
                'verbose_name_plural': 'Website Settings',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin_staff', 'Admin Staff'), ('client', 'Client'), ('client_staff', 'Client Staff')], default='client', max_length=20)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='staff_imgs/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_folder_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('image_folder_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('image_folder_suffix', models.CharField(blank=True, max_length=5, null=True)),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='clients_imgs/')),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('perm_staff_list', models.BooleanField(default=False)),
                ('perm_staff_add', models.BooleanField(default=False)),
                ('perm_staff_edit', models.BooleanField(default=False)),
                ('perm_staff_delete', models.BooleanField(default=False)),
                ('perm_staff_status', models.BooleanField(default=False)),
                ('perm_idcard_setting_list', models.BooleanField(default=False)),
                ('perm_idcard_setting_add', models.BooleanField(default=False)),
                ('perm_idcard_setting_edit', models.BooleanField(default=False)),
                ('perm_idcard_setting_delete', models.BooleanField(default=False)),
                ('perm_idcard_setting_status', models.BooleanField(default=False)),
                ('perm_idcard_pending_list', models.BooleanField(default=False)),
                ('perm_idcard_verified_list', models.BooleanField(default=False)),
                ('perm_idcard_pool_list', models.BooleanField(default=False)),
                ('perm_idcard_approved_list', models.BooleanField(default=False)),
                ('perm_idcard_download_list', models.BooleanField(default=False)),
                ('perm_idcard_reprint_list', models.BooleanField(default=False)),
                ('perm_idcard_add', models.BooleanField(default=False)),
                ('perm_idcard_edit', models.BooleanField(default=False)),
                ('perm_idcard_delete', models.BooleanField(default=False)),
                ('perm_idcard_info', models.BooleanField(default=False)),
                ('perm_idcard_approve', models.BooleanField(default=False)),
                ('perm_idcard_verify', models.BooleanField(default=False)),
                ('perm_idcard_bulk_upload', models.BooleanField(default=False)),
                ('perm_idcard_bulk_download', models.BooleanField(default=False)),
                ('perm_idcard_created_at', models.BooleanField(default=False)),
                ('perm_idcard_updated_at', models.BooleanField(default=False)),
                ('perm_idcard_delete_from_pool', models.BooleanField(default=False)),
                ('perm_delete_all_idcard', models.BooleanField(default=False)),
                ('perm_reupload_idcard_image', models.BooleanField(default=False)),
                ('perm_idcard_retrieve', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IDCardGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('template_front', models.ImageField(blank=True, null=True, upload_to='id_templates/')),
                ('template_back', models.ImageField(blank=True, null=True, upload_to='id_templates/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_card_groups', to='core.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IDCardTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fields', models.JSONField(default=list, help_text='List of field configurations: [{name, type, order}]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='core.idcardgroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_data', models.JSONField(default=dict, help_text='Dynamic field values based on table fields')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='id_photos/')),
                ('original_photo_name', models.CharField(blank=True, help_text='Original photo name from Excel for matching', max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('pool', 'In Pool'), ('approved', 'Approved'), ('download', 'Downloaded'), ('reprint', 'Reprint')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to='core.idcardtable')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_type', models.CharField(choices=[('admin_staff', 'Admin Staff'), ('client_staff', 'Client Staff')], max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('perm_staff_list', models.BooleanField(default=False)),
                ('perm_staff_add', models.BooleanField(default=False)),
                ('perm_staff_edit', models.BooleanField(default=False)),
                ('perm_staff_delete', models.BooleanField(default=False)),
                ('perm_staff_status', models.BooleanField(default=False)),
                ('perm_idcard_setting_list', models.BooleanField(default=False)),
                ('perm_idcard_setting_add', models.BooleanField(default=False)),
                ('perm_idcard_setting_edit', models.BooleanField(default=False)),
                ('perm_idcard_setting_delete', models.BooleanField(default=False)),
                ('perm_idcard_setting_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='core.client')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Staff',
                'ordering': ['-created_at'],
            },
        ),
    ]
