# Generated by Django 5.2.10 on 2026-02-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='assigned_clients',
            field=models.ManyToManyField(blank=True, related_name='assigned_admin_staff', to='core.client'),
        ),
    ]
