# Generated by Django 5.2.10 on 2026-02-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_assigned_clients_to_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='field_data',
            field=models.JSONField(default=dict, help_text='Dynamic field values based on table fields. NOTE: Image paths here are deprecated - use CardMedia model.'),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='photo',
            field=models.ImageField(blank=True, help_text='DEPRECATED: Use CardMedia model for new photos', null=True, upload_to='id_photos/'),
        ),
        migrations.AlterField(
            model_name='idcardgroup',
            name='template_back',
            field=models.ImageField(blank=True, help_text='DEPRECATED: Use CardMedia model for new templates', null=True, upload_to='id_templates/'),
        ),
        migrations.AlterField(
            model_name='idcardgroup',
            name='template_front',
            field=models.ImageField(blank=True, help_text='DEPRECATED: Use CardMedia model for new templates', null=True, upload_to='id_templates/'),
        ),
    ]
