# Generated by Django 5.2.10 on 2026-02-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_admin_staff_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='perm_staff_add',
        ),
        migrations.RemoveField(
            model_name='client',
            name='perm_staff_delete',
        ),
        migrations.RemoveField(
            model_name='client',
            name='perm_staff_edit',
        ),
        migrations.RemoveField(
            model_name='client',
            name='perm_staff_list',
        ),
        migrations.RemoveField(
            model_name='client',
            name='perm_staff_status',
        ),
        migrations.AddField(
            model_name='client',
            name='perm_idcard_client_list',
            field=models.BooleanField(default=False),
        ),
    ]
