# Generated by Django 5.2.10 on 2026-02-08 10:35

from django.db import migrations, models


def update_existing_clients(apps, schema_editor):
    """
    Update all existing Client records to have the new default=True values.
    Only sets fields that are currently False to True.
    This ensures existing clients get the same permissions as new clients.
    """
    Client = apps.get_model('core', 'Client')
    fields_to_enable = [
        'perm_idcard_client_list',
        'perm_idcard_pending_list',
        'perm_idcard_verified_list',
        'perm_idcard_pool_list',
        'perm_idcard_approved_list',
        'perm_idcard_download_list',
        'perm_idcard_add',
        'perm_idcard_edit',
        'perm_idcard_delete',
        'perm_idcard_info',
        'perm_idcard_approve',
        'perm_idcard_verify',
        'perm_idcard_bulk_upload',
        'perm_idcard_bulk_download',
        'perm_reupload_idcard_image',
        'perm_idcard_retrieve',
    ]
    update_kwargs = {field: True for field in fields_to_enable}
    db_alias = schema_editor.connection.alias
    count = Client.objects.using(db_alias).update(**update_kwargs)
    # Note: migration output is intentionally silent; check via Django admin if needed.


def reverse_update(apps, schema_editor):
    """Reverse: set all 16 fields back to False for all clients."""
    Client = apps.get_model('core', 'Client')
    fields_to_disable = [
        'perm_idcard_client_list',
        'perm_idcard_pending_list',
        'perm_idcard_verified_list',
        'perm_idcard_pool_list',
        'perm_idcard_approved_list',
        'perm_idcard_download_list',
        'perm_idcard_add',
        'perm_idcard_edit',
        'perm_idcard_delete',
        'perm_idcard_info',
        'perm_idcard_approve',
        'perm_idcard_verify',
        'perm_idcard_bulk_upload',
        'perm_idcard_bulk_download',
        'perm_reupload_idcard_image',
        'perm_idcard_retrieve',
    ]
    update_kwargs = {field: False for field in fields_to_disable}
    db_alias = schema_editor.connection.alias
    Client.objects.using(db_alias).update(**update_kwargs)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_change_permission_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='perm_idcard_add',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='perm_idcard_approve',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='perm_idcard_approved_list',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='perm_idcard_bulk_download',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='perm_idcard_bulk_upload',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='perm_idcard_client_list',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='perm_idcard_delete',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='perm_idcard_download_list',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='perm_idcard_edit',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='perm_idcard_info',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='perm_idcard_pending_list',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='perm_idcard_pool_list',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='perm_idcard_retrieve',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='perm_idcard_verified_list',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='perm_idcard_verify',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='perm_reupload_idcard_image',
            field=models.BooleanField(default=True),
        ),
        # Data migration: update all existing clients to match new defaults
        migrations.RunPython(update_existing_clients, reverse_update),
    ]
