# Generated by Django 5.2.10 on 2026-02-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_change_client_permission_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='assigned_groups',
            field=models.ManyToManyField(blank=True, help_text='ID Card groups this staff can manage. Empty = all groups.', related_name='assigned_staff', to='core.idcardgroup'),
        ),
    ]
