# Generated by Django 5.2.10 on 2026-02-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_group_create_delete_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='perm_website_add',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_website_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_website_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_website_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_website_view',
            field=models.BooleanField(default=False),
        ),
    ]
