# Generated by Django 5.2.10 on 2026-02-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_staff_perm_website_add_staff_perm_website_delete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('pool', 'In Pool'), ('approved', 'Approved'), ('download', 'Downloaded'), ('reprint', 'Reprint')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='reprintrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('downloaded', 'Downloaded')], db_index=True, default='requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(choices=[('admin_staff', 'Admin Staff'), ('client_staff', 'Client Staff')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin_staff', 'Admin Staff'), ('client', 'Client'), ('client_staff', 'Client Staff')], db_index=True, default='client', max_length=20),
        ),
    ]
