# Generated by Django 5.2.10 on 2026-02-10 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_db_indexes_for_performance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Logged in'), ('logout', 'Logged out'), ('client_create', 'Client created'), ('client_update', 'Client updated'), ('client_delete', 'Client deleted'), ('client_status', 'Client status changed'), ('staff_create', 'Staff created'), ('staff_update', 'Staff updated'), ('staff_delete', 'Staff deleted'), ('staff_status', 'Staff status changed'), ('card_create', 'ID cards added'), ('card_update', 'ID card updated'), ('card_delete', 'ID card deleted'), ('card_status', 'Card status changed'), ('card_bulk_status', 'Bulk card status change'), ('card_bulk_upload', 'Bulk card upload'), ('card_bulk_download', 'Bulk card download'), ('image_upload', 'Images uploaded'), ('image_reupload', 'Images re-uploaded'), ('group_create', 'Group created'), ('group_update', 'Group updated'), ('group_delete', 'Group deleted'), ('table_create', 'Table created'), ('table_update', 'Table updated'), ('table_delete', 'Table deleted'), ('bulk_delete', 'Bulk delete'), ('bulk_upgrade', 'Bulk upgrade'), ('website_update', 'Website content updated'), ('reprint_request', 'Reprint requested'), ('reprint_status', 'Reprint status changed'), ('settings_update', 'Settings updated'), ('other', 'Other action')], db_index=True, max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('target_model', models.CharField(blank=True, default='', max_length=50)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_name', models.CharField(blank=True, default='', max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'action'], name='actlog_time_action_idx')],
            },
        ),
    ]
