# Generated by Django 5.2.10 on 2026-02-11 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_activity_log_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
