# Generated by Django 5.2.10 on 2026-02-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_profile_image_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='perm_idcard_bulk_reupload',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='perm_idcard_upgrade_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_idcard_bulk_reupload',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_idcard_upgrade_all',
            field=models.BooleanField(default=False),
        ),
    ]
