# Generated by Django 5.2.10 on 2026-02-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0018_add_background_task_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RenameIndex(
            model_name='backgroundtask',
            new_name='core_backgr_user_id_7301af_idx',
            old_name='core_backgr_user_id_5b9e4b_idx',
        ),
        migrations.RenameIndex(
            model_name='backgroundtask',
            new_name='core_backgr_task_ty_a10807_idx',
            old_name='core_backgr_task_ty_d1f9c0_idx',
        ),
        migrations.AddIndex(
            model_name='backgroundtask',
            index=models.Index(fields=['created_at'], name='core_backgr_created_d8ad5b_idx'),
        ),
        migrations.AddIndex(
            model_name='backgroundtask',
            index=models.Index(fields=['completed_at'], name='core_backgr_complet_426798_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['created_at'], name='core_client_created_f91eae_idx'),
        ),
        migrations.AddIndex(
            model_name='idcard',
            index=models.Index(fields=['table', 'status'], name='core_idcard_table_i_85127c_idx'),
        ),
        migrations.AddIndex(
            model_name='idcard',
            index=models.Index(fields=['created_at'], name='core_idcard_created_ff3f57_idx'),
        ),
        migrations.AddIndex(
            model_name='idcardgroup',
            index=models.Index(fields=['is_active'], name='core_idcard_is_acti_5b1224_idx'),
        ),
        migrations.AddIndex(
            model_name='idcardgroup',
            index=models.Index(fields=['created_at'], name='core_idcard_created_a4a833_idx'),
        ),
        migrations.AddIndex(
            model_name='idcardtable',
            index=models.Index(fields=['is_active'], name='core_idcard_is_acti_774067_idx'),
        ),
        migrations.AddIndex(
            model_name='idcardtable',
            index=models.Index(fields=['created_at'], name='core_idcard_created_100402_idx'),
        ),
        migrations.AddIndex(
            model_name='reprintrequest',
            index=models.Index(fields=['table', 'status'], name='core_reprin_table_i_e758bf_idx'),
        ),
        migrations.AddIndex(
            model_name='reprintrequest',
            index=models.Index(fields=['created_at'], name='core_reprin_created_8186a9_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['created_at'], name='core_staff_created_c8f0a1_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='core_user_email_38052c_idx'),
        ),
    ]
