# Generated by Django 5.2.10 on 2026-02-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_production_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='idcard',
            index=models.Index(fields=['updated_at'], name='core_idcard_updated_8223db_idx'),
        ),
        migrations.AddIndex(
            model_name='idcardgroup',
            index=models.Index(fields=['client', 'is_active'], name='core_idcard_client__4e7510_idx'),
        ),
    ]
