# Generated by Django 5.2.10 on 2026-02-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_observability_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', '-created_at'], name='actlog_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='backgroundtask',
            index=models.Index(fields=['user', '-created_at'], name='core_backgr_user_id_4b7803_idx'),
        ),
        migrations.AddIndex(
            model_name='backgroundtask',
            index=models.Index(fields=['status', '-created_at'], name='core_backgr_status_7fe599_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['status', '-created_at'], name='core_client_status_cb2b5e_idx'),
        ),
        migrations.AddIndex(
            model_name='idcard',
            index=models.Index(fields=['status', 'created_at'], name='core_idcard_status_a9d94a_idx'),
        ),
        migrations.AddIndex(
            model_name='idcard',
            index=models.Index(fields=['table', 'created_at'], name='core_idcard_table_i_a6fa6f_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['staff_type', 'created_at'], name='core_staff_staff_t_81deb4_idx'),
        ),
    ]
