# Generated by Django 5.2.10 on 2026-02-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_perf_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcard',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when card was moved to pool', null=True),
        ),
        migrations.AddField(
            model_name='idcard',
            name='downloaded_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when card was moved to downloaded status', null=True),
        ),
    ]
