# Generated by Django 5.2.10 on 2026-02-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_downloaded_at_deleted_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='idcard',
            index=models.Index(fields=['table', 'status', '-id'], name='idcard_tbl_status_id_desc'),
        ),
        migrations.AddIndex(
            model_name='idcard',
            index=models.Index(fields=['downloaded_at'], name='idcard_downloaded_at_idx'),
        ),
        migrations.AddIndex(
            model_name='idcard',
            index=models.Index(fields=['deleted_at'], name='idcard_deleted_at_idx'),
        ),
    ]
