# Generated by Django 5.2.10 on 2026-02-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_gin_index_field_data'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='idcardtable',
            index=models.Index(fields=['group', 'is_active'], name='core_idcard_group_i_a1a0c9_idx'),
        ),
        migrations.AddIndex(
            model_name='reprintrequest',
            index=models.Index(fields=['table', 'status', '-created_at'], name='core_reprin_table_i_490be1_idx'),
        ),
        migrations.AddIndex(
            model_name='reprintrequest',
            index=models.Index(fields=['card'], name='core_reprin_card_id_b9716c_idx'),
        ),
    ]
