# Generated by Django 5.2.10 on 2026-02-22 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=10)),
                ('category', models.CharField(choices=[('general', 'General'), ('announcement', 'Announcement'), ('update', 'System Update'), ('maintenance', 'Maintenance'), ('alert', 'Alert')], db_index=True, default='general', max_length=20)),
                ('target', models.CharField(choices=[('all', 'All Users'), ('super_admin', 'Super Admins'), ('admin_staff', 'Admin Staff'), ('client', 'Clients'), ('client_staff', 'Client Staff'), ('selected', 'Selected Users')], default='all', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('target_users', models.ManyToManyField(blank=True, related_name='targeted_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='core.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-created_at', 'target'], name='notif_time_target_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_active', '-created_at'], name='notif_active_time_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationread',
            index=models.Index(fields=['user', '-read_at'], name='notifread_user_time_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationread',
            unique_together={('user', 'notification')},
        ),
    ]
