# Generated by Django 5.2.10 on 2026-02-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_notification_notificationread_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name shown in the download dropdown', max_length=100, unique=True)),
                ('instructions', models.TextField(help_text='Footer instructions printed at the bottom of PDF/Word exports')),
                ('is_default', models.BooleanField(default=False, help_text='Mark as default selection in download modals')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Export Template',
                'verbose_name_plural': 'Export Templates',
                'ordering': ['name'],
            },
        ),
    ]
