# Generated by Django 5.2.10 on 2026-02-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_add_export_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='perm_mobile_app',
            field=models.BooleanField(default=False, help_text='Allow access to mobile PWA app'),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_mobile_app',
            field=models.BooleanField(default=False, help_text='Allow access to mobile PWA app'),
        ),
    ]
