# Generated by Django 5.2.10 on 2026-02-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_add_perm_mobile_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='allowed_classes',
            field=models.JSONField(blank=True, default=list, help_text='Allowed class values. Empty list = all classes.'),
        ),
        migrations.AddField(
            model_name='staff',
            name='allowed_sections',
            field=models.JSONField(blank=True, default=list, help_text='Allowed section values. Empty list = all sections.'),
        ),
    ]
