# Generated by Django 5.2.10 on 2026-02-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_staff_class_section_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='original_photo_name',
            field=models.CharField(blank=True, db_index=True, help_text='Original photo name from Excel for matching', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['client', 'staff_type'], name='core_staff_client__51d547_idx'),
        ),
    ]
