# Generated by Django 5.2.10 on 2026-02-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0030_alter_client_name_alter_idcard_original_photo_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='core_user_email_38052c_idx',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_user_email'),
        ),
    ]
