# Generated by Django 5.2.10 on 2026-02-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_unique_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropperRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Semantic version string, e.g. "3.0.1"', max_length=30, unique=True)),
                ('download_url', models.URLField(help_text='Direct URL to the installer EXE (GitHub Release asset or self-hosted).', max_length=500)),
                ('changelog', models.TextField(blank=True, default='', help_text='Human-readable changelog / release notes (Markdown OK).')),
                ('is_latest', models.BooleanField(db_index=True, default=False, help_text='Only one release should be marked as latest at a time.')),
                ('released_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cropper Release',
                'verbose_name_plural': 'Cropper Releases',
                'ordering': ['-released_at'],
            },
        ),
    ]
