# Generated by Django 5.2.10 on 2026-02-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_cropper_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reprintrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('downloaded', 'Downloaded'), ('pool', 'Pool')], db_index=True, default='requested', max_length=20),
        ),
    ]
