# Generated by Django 5.2.10 on 2026-02-28 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_all_perm_defaults_off'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='pending', max_length=20)),
                ('confirmation_code', models.CharField(max_length=10)),
                ('client_ids', models.JSONField(blank=True, default=list)),
                ('client_names', models.JSONField(blank=True, default=dict)),
                ('progress', models.IntegerField(default=0, help_text='Number of clients processed')),
                ('total', models.IntegerField(default=0, help_text='Total number of clients to process')),
                ('current_client', models.CharField(blank=True, default='', max_length=200)),
                ('zip_files', models.JSONField(blank=True, default=dict)),
                ('auto_delete_at', models.DateTimeField(blank=True, help_text='When the backup files will be automatically deleted', null=True)),
                ('is_auto_delete_cancelled', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup Task',
                'verbose_name_plural': 'Backup Tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='core_backup_status_dda238_idx'), models.Index(fields=['auto_delete_at'], name='core_backup_auto_de_287a00_idx')],
            },
        ),
    ]
