# Generated by Django 5.2.10 on 2026-02-28 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_backup_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='perm_idcard_group_create',
        ),
        migrations.RemoveField(
            model_name='client',
            name='perm_idcard_group_delete',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='perm_delete_all_idcard',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='perm_idcard_group_create',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='perm_idcard_group_delete',
        ),
    ]
