# Generated by Django 5.2.10 on 2026-02-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_perm_delete_all_idcard_from_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='perm_confirmed_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_finalized_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='perm_print_list',
            field=models.BooleanField(default=False),
        ),
    ]
