# Generated by Django 5.2.10 on 2026-03-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_add_print_reprint_list_perms_to_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_email', models.EmailField(db_index=True, max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('email_type', models.CharField(choices=[('welcome', 'Welcome / Activation'), ('temp_password', 'Temp Password'), ('password_change', 'Password Change Notice')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('on_hold', 'On Hold'), ('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='welcome_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
