# Generated by Django 5.2.10 on 2026-03-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_idcardtable_deleted_by_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='allowed_branches',
            field=models.JSONField(blank=True, default=list, help_text='Allowed branch values (colleges). Empty list = all branches.'),
        ),
    ]
