# Generated by Django 5.2.10 on 2026-03-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_add_allowed_branches_to_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcard',
            name='modified_by',
            field=models.CharField(blank=True, default='', help_text='Username of the user who last modified this card', max_length=150),
        ),
    ]
