# Generated by Django 5.2.10 on 2026-03-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_add_status_changed_at_to_idcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporttemplate',
            name='font_name',
            field=models.CharField(choices=[('arial', 'English (Arial)'), ('hindi', 'Hindi (Abbasi)')], default='arial', help_text='Font used for instructions: arial (English) or hindi (Abbasi)', max_length=10),
        ),
        migrations.AddField(
            model_name='exporttemplate',
            name='is_bold',
            field=models.BooleanField(default=False, help_text='Render instructions in bold'),
        ),
    ]
