# Generated by Django 5.2.10 on 2026-03-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_add_font_fields_to_exporttemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('pro_user', 'Pro User'), ('super_admin', 'Super Admin'), ('admin_staff', 'Admin Staff'), ('client', 'Client'), ('client_staff', 'Client Staff')], db_index=True, default='client', max_length=20),
        ),
    ]
