# Generated by Django 5.2.10 on 2026-03-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_add_client_perm_set_temp_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='perm_idcard_created_at',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='perm_idcard_created_at',
        ),
    ]
