# Generated by Django 5.2.10 on 2026-03-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_add_client_reprint_request_confirmed_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='assignment_scopes',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Per-scope class/section/branch filters for client staff assignments.',
            ),
        ),
    ]
