# Generated by Django 5.2.10 on 2026-04-04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_add_staff_assignment_scopes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('scope', models.CharField(choices=[('client_only', 'Client Only'), ('client_and_staff', 'Client + Staff')], db_index=True, default='client_only', max_length=20)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_messages', to='core.client')),
                ('notification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_message', to='core.notification')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_client_messages', to='core.user')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['client', '-created_at'], name='climsg_client_time_idx'),
                    models.Index(fields=['scope', '-created_at'], name='climsg_scope_time_idx'),
                ],
            },
        ),
    ]
