# Generated by Django 5.2.10 on 2026-04-04 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_activitylog_action'),
        ('core', '0054_clientmessage'),
    ]

    operations = [
    ]
