# Generated by Django 5.2.10 on 2026-04-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_merge_20260404_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmessage',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='clientmessage',
            name='visibility',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary')], db_index=True, default='permanent', max_length=12),
        ),
        migrations.AddIndex(
            model_name='clientmessage',
            index=models.Index(fields=['visibility', 'expires_at'], name='climsg_visibility_exp_idx'),
        ),
    ]
