# Generated by Django 5.2.10 on 2026-04-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_clientmessage_expires_at_clientmessage_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_active', 'expires_at'], name='notif_active_exp_idx'),
        ),
    ]
