# Generated by Django 5.2.10 on 2026-04-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_client_website_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='perm_manage_client_staff',
            field=models.BooleanField(default=False),
        ),
    ]
