# Generated by Django 5.2.12 on 2026-04-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_staff_perm_manage_client_staff'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='idcard',
            index=models.Index(fields=['table', 'status', '-status_changed_at', '-id'], name='idc_tbl_st_chg_id_idx'),
        ),
        migrations.AddIndex(
            model_name='idcard',
            index=models.Index(fields=['table', 'status', '-downloaded_at', '-id'], name='idc_tbl_st_dld_id_idx'),
        ),
        migrations.AddIndex(
            model_name='idcard',
            index=models.Index(fields=['table', 'status', '-deleted_at', '-id'], name='idc_tbl_st_del_id_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['client', 'staff_type', '-created_at'], name='staff_client_type_time_idx'),
        ),
    ]
