# Generated by Django 5.2.12 on 2026-04-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_merge_20260416_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Logged in'), ('logout', 'Logged out'), ('password_reset', 'Password reset completed'), ('impersonate_start', 'Impersonation started'), ('impersonate_stop', 'Impersonation stopped'), ('client_create', 'Client created'), ('client_update', 'Client updated'), ('client_delete', 'Client deleted'), ('client_status', 'Client status changed'), ('staff_create', 'Staff created'), ('staff_update', 'Staff updated'), ('staff_assignment', 'Staff assignment updated'), ('staff_delete', 'Staff deleted'), ('staff_status', 'Staff status changed'), ('staff_password_reset', 'Staff password reset'), ('card_create', 'ID cards added'), ('card_update', 'ID card updated'), ('card_delete', 'ID card deleted'), ('card_status', 'Card status changed'), ('card_bulk_status', 'Bulk card status change'), ('card_bulk_upload', 'Bulk card upload'), ('card_bulk_download', 'Bulk card download'), ('image_upload', 'Images uploaded'), ('image_reupload', 'Images re-uploaded'), ('group_create', 'Group created'), ('group_update', 'Group updated'), ('group_delete', 'Group deleted'), ('table_create', 'Table created'), ('table_update', 'Table updated'), ('table_delete', 'Table deleted'), ('bulk_delete', 'Bulk delete'), ('bulk_upgrade', 'Bulk upgrade'), ('website_update', 'Website content updated'), ('notification_create', 'Notification created'), ('notification_delete', 'Notification deleted'), ('email_send', 'Email sent'), ('email_resend', 'Email resent'), ('backup_initiate', 'Backup initiated'), ('backup_start', 'Backup started'), ('backup_delete', 'Backup deleted'), ('reprint_request', 'Reprint requested'), ('reprint_status', 'Reprint status changed'), ('settings_update', 'Settings updated'), ('other', 'Other action')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='exporttemplate',
            name='instructions',
            field=models.TextField(help_text='Footer text printed on each PDF/Word page when this template is selected'),
        ),
    ]
