# Generated by Django 5.2.12 on 2026-04-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_move_officework_models_to_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_temp_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='temp_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
