# Generated by Django 5.2.12 on 2026-04-25 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_user_is_temp_password_user_temp_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_temp_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='temp_password',
        ),
    ]
