# Generated by Django 5.2.12 on 2026-05-06 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_client_website_logo_cover_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='perm_print_list',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='perm_finalized_list',
        ),
    ]
