# Generated by Django 5.2.12 on 2026-05-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_remove_print_finalized_perms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CropperRelease',
        ),
    ]
