# Generated by Django 5.2.12 on 2026-05-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_remove_staff_manage_website_section_perms'),
    ]

    operations = [
    ]
