# Generated by Django 5.2.12 on 2026-05-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_delete_websitesettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='client_logos/'),
        ),
    ]
