# Generated by Django 5.2.12 on 2026-05-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_client_logo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['status', 'created_at'], name='core_client_status_created_idx'),
        ),
    ]
