# Generated by Django 5.2.12 on 2026-05-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_client_status_created_at_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_guest',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('pro_user', 'Pro User'), ('super_admin', 'Super Admin'), ('admin_staff', 'Admin Staff'), ('client', 'Client'), ('guest_user', 'Guest User'), ('client_staff', 'Client Staff')], db_index=True, default='client', max_length=20),
        ),
    ]
