# Generated by Copilot on 2026-05-30

from django.contrib.auth.hashers import make_password
from django.db import migrations


DEMO_USERNAME = 'demo'
DEMO_EMAIL = 'demo@adarshbhopal.in'
DEMO_PASSWORD = 'Demo@1234'
DEMO_NAME = 'Demo Guest User'


def seed_demo_mobile_client(apps, schema_editor):
    User = apps.get_model('core', 'User')
    Client = apps.get_model('core', 'Client')
    db_alias = schema_editor.connection.alias

    user = User.objects.using(db_alias).filter(email=DEMO_EMAIL).first() or User.objects.using(db_alias).filter(username=DEMO_USERNAME).first()
    if user is None:
        user = User(username=DEMO_USERNAME, email=DEMO_EMAIL, role='guest_user', is_active=True)
    else:
        user.username = DEMO_USERNAME
        user.email = DEMO_EMAIL
        user.role = 'guest_user'
        user.is_active = True

    user.password = make_password(DEMO_PASSWORD)
    user.save(using=db_alias)

    client = Client.objects.using(db_alias).filter(user_id=user.pk).first()
    if client is None:
        client = Client(user_id=user.pk, name=DEMO_NAME, status='active', is_guest=True)

    client.name = DEMO_NAME
    client.status = 'active'
    client.is_guest = True
    client.perm_mobile_app = True
    client.perm_idcard_pending_list = True
    client.perm_idcard_verified_list = True
    client.perm_idcard_pool_list = True
    client.perm_idcard_approved_list = True
    client.perm_idcard_download_list = True
    client.perm_idcard_reprint_list = True
    client.perm_reprint_request_list = True
    client.perm_confirmed_list = True
    client.perm_idcard_info = True
    client.save(using=db_alias)


def unseed_demo_mobile_client(apps, schema_editor):
    User = apps.get_model('core', 'User')
    Client = apps.get_model('core', 'Client')
    db_alias = schema_editor.connection.alias

    client = Client.objects.using(db_alias).filter(user__email=DEMO_EMAIL).first() or Client.objects.using(db_alias).filter(user__username=DEMO_USERNAME).first()
    if client is not None:
        client.delete(using=db_alias)

    user = User.objects.using(db_alias).filter(email=DEMO_EMAIL).first() or User.objects.using(db_alias).filter(username=DEMO_USERNAME).first()
    if user is not None:
        user.delete(using=db_alias)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_client_is_guest_alter_user_role'),
    ]

    operations = [
        migrations.RunPython(seed_demo_mobile_client, reverse_code=unseed_demo_mobile_client),
    ]