# Generated by Django 5.2.12 on 2026-06-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_seed_demo_mobile_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='logo',
        ),
        migrations.AddField(
            model_name='client',
            name='icon',
            field=models.CharField(default='fa-solid fa-building', max_length=100),
        ),
        migrations.DeleteModel(
            name='SuperModeAssignment',
        ),
    ]
