# Generated by Django 5.2.12 on 2026-06-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_cleanup_orphaned_officework_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='perm_idcard_clear_pending_path',
            field=models.BooleanField(default=False),
        ),
    ]
