# Generated by Django 5.2.12 on 2026-06-27 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_staff_perm_idcard_clear_pending_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(choices=[('admin_staff', 'Admin Staff'), ('client_staff', 'Client Staff'), ('photographer', 'Photographer')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('pro_user', 'Pro User'), ('super_admin', 'Super Admin'), ('admin_staff', 'Admin Staff'), ('client', 'Client'), ('guest_user', 'Guest User'), ('client_staff', 'Client Staff'), ('photographer', 'Photographer')], db_index=True, default='client', max_length=20),
        ),
        migrations.CreateModel(
            name='PhotographerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photographer_assignments', to='core.client')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photographer_assignments', to='core.staff')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('photographer', 'client')},
            },
        ),
    ]
