# Generated by Django 5.2.12 on 2026-06-27 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_alter_staff_staff_type_alter_user_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='address',
        ),
    ]
