# Generated by Django 5.2.12 on 2026-06-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_remove_client_address_remove_staff_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographerassignment',
            name='allowed_table_ids',
            field=models.JSONField(blank=True, default=list, help_text='Table IDs this photographer can see for this client. Empty = all tables.'),
        ),
    ]
