# Generated by Django 5.2.12 on 2026-06-28 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_photographerassignment_allowed_table_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('pro_user', 'Pro User'), ('super_admin', 'Super Admin'), ('operator', 'Operator'), ('client', 'Client'), ('guest_user', 'Guest User'), ('assistant', 'Assistant'), ('photographer', 'Photographer')], db_index=True, default='client', max_length=20),
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('perm_idcard_pending_list', models.BooleanField(default=False)),
                ('perm_idcard_verified_list', models.BooleanField(default=False)),
                ('perm_idcard_add', models.BooleanField(default=False)),
                ('perm_idcard_info', models.BooleanField(default=False)),
                ('perm_mobile_app', models.BooleanField(default=False)),
                ('perm_idcard_bulk_download', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photographer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Photographer',
                'verbose_name_plural': 'Photographers',
                'ordering': ['-created_at'],
            },
        ),
    ]
