# Generated by Django 5.2.12 on 2026-07-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_enable_photographer_mobile_app_perm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='perm_mobile_app',
            field=models.BooleanField(default=True),
        ),
    ]
