# Generated by Django 5.2.12 on 2026-08-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_add_table_type_to_idcardtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='org_type',
            field=models.CharField(choices=[('school', 'School'), ('college', 'College'), ('company', 'Company / Corporate'), ('other', 'Other')], db_index=True, default='school', help_text='Type of organisation: school, college, company, or other', max_length=20),
        ),
    ]
