# Generated by Django 5.2.12 on 2026-08-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_client_org_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('approved', 'Approved'), ('printed', 'Printed'), ('request', 'Requested'), ('deleted', 'Deleted'), ('download', 'Downloaded'), ('pool', 'In Pool'), ('reprint', 'Reprint')], db_index=True, default='pending', max_length=20),
        ),
    ]
