# Generated by Django 5.2.12 on 2026-08-12 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0002_initial_domain_models'),
        ('core', '0103_initial_domain_models'),
        ('mediafiles', '0006_initial_domain_models'),
        ('operators', '0003_initial_domain_models'),
        ('tables', '0001_initial_domain_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reprintrequest',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reprint_requests', to='tables.idcard'),
        ),
        migrations.RemoveField(
            model_name='idcardtable',
            name='group',
        ),
        migrations.AlterField(
            model_name='reprintrequest',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reprint_requests', to='tables.table'),
        ),
        migrations.AlterModelOptions(
            name='clientpresencesession',
            options={'verbose_name': 'Organisation Presence Session', 'verbose_name_plural': 'Organisation Presence Sessions'},
        ),
        migrations.AddField(
            model_name='organisation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientmessage',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_messages', to='core.organisation'),
        ),
        migrations.AlterField(
            model_name='clientpresencesession',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_sessions', to='core.organisation'),
        ),
        migrations.AlterField(
            model_name='photographerassignment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photographer_assignments', to='core.organisation'),
        ),
        migrations.DeleteModel(
            name='IDCard',
        ),
        migrations.DeleteModel(
            name='IDCardGroup',
        ),
        migrations.DeleteModel(
            name='IDCardTable',
        ),
        migrations.AddIndex(
            model_name='organisation',
            index=models.Index(fields=['status', '-created_at'], name='core_client_status_cb2b5e_idx'),
        ),
        migrations.AddIndex(
            model_name='organisation',
            index=models.Index(fields=['created_at'], name='core_client_created_f91eae_idx'),
        ),
        migrations.AddIndex(
            model_name='organisation',
            index=models.Index(fields=['status', 'created_at'], name='core_client_status_created_idx'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
