# Generated by Django 5.2.12 on 2026-08-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_initial_domain_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target',
            field=models.CharField(choices=[('all', 'All Users'), ('super_admin', 'Super Admins'), ('admin_staff', 'Admin Staff / Operators'), ('prime_manager', 'Prime Managers'), ('manager', 'Managers'), ('assistant', 'Assistants'), ('selected', 'Selected Users')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('pro_user', 'Pro User'), ('super_admin', 'Super Admin'), ('operator', 'Operator'), ('prime_manager', 'Prime Manager'), ('manager', 'Manager'), ('guest_prime_manager', 'Guest Prime Manager'), ('assistant', 'Assistant'), ('photographer', 'Photographer')], db_index=True, default='prime_manager', max_length=30),
        ),
    ]
