# Generated by Django 5.2.12 on 2026-08-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_add_org_role_to_organisation'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='organisation',
                    name='org_type',
                    field=models.CharField(choices=[('school', 'School'), ('college', 'College'), ('company', 'Company / Corporate'), ('other', 'Other')], db_column='client_type', db_index=True, default='school', help_text='Type of organisation: school, college, company, or other', max_length=20),
                ),
                migrations.AlterField(
                    model_name='organisation',
                    name='perm_organisation_list',
                    field=models.BooleanField(db_column='perm_idcard_client_list', default=False),
                ),
            ],
            database_operations=[]
        )
    ]
