# Generated by Django 5.2.12 on 2026-08-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_add_client_id_to_idcardtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('prime_admin', 'Prime Admin'), ('super_admin', 'Super Admin'), ('operator', 'Operator'), ('prime_manager', 'Prime Manager'), ('super_manager', 'Super Manager'), ('assistant', 'Assistant'), ('photographer', 'Photographer')], db_index=True, default='prime_manager', max_length=30),
        ),
    ]
