# Generated by Django 5.2.12 on 2026-08-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_user_must_change_password_user_temp_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='max_super_managers',
            field=models.PositiveIntegerField(default=4, help_text='Configurable maximum number of Super Managers allowed for this organisation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('prime_admin', 'Prime Admin'), ('super_admin', 'Super Admin'), ('operator', 'Operator'), ('photographer', 'Photographer'), ('prime_manager', 'Prime Manager'), ('super_manager', 'Super Manager'), ('guest_manager', 'Guest Manager'), ('assistant', 'Assistant')], db_index=True, default='prime_manager', max_length=30),
        ),
    ]
