# Generated by Django 5.2.7 on 2026-08-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_organisation_max_super_managers_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='max_retries',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='retry_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(choices=[('welcome', 'Welcome / Activation'), ('temp_password', 'Temp Password'), ('password_change', 'Password Change Notice'), ('otp_reset', 'Password Reset OTP'), ('notification', 'Notification Alert'), ('system', 'System / Custom')], db_index=True, default='system', max_length=30),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('on_hold', 'On Hold'), ('pending', 'Pending'), ('sending', 'Sending'), ('retry', 'Retrying'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target',
            field=models.CharField(choices=[('all', 'All Users'), ('super_admin', 'Super Admins'), ('operator', 'Admin Staff / Operators'), ('prime_manager', 'Prime Managers (Organisations)'), ('super_manager', 'Super Managers'), ('manager', 'Managers'), ('assistant', 'Assistants'), ('photographer', 'Photographers'), ('selected', 'Selected Users')], default='all', max_length=20),
        ),
    ]
