# Generated by Django 5.2.7 on 2026-08-23 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_emaillog_last_attempt_at_emaillog_max_retries_and_more'),
        ('tables', '0005_rename_core_idcard_organis_65641d_idx_core_idcard_client__2687fe_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reprintrequest',
            name='changes',
            field=models.JSONField(blank=True, default=dict, help_text='Staged field updates applied upon confirmation'),
        ),
        migrations.AddField(
            model_name='reprintrequest',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reprintrequest',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reprint_requests_confirmed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reprintrequest',
            name='reprint_number',
            field=models.PositiveIntegerField(default=1, help_text='Sequential reprint number for this card (1=first reprint, 2=second, etc.)'),
        ),
        migrations.AlterField(
            model_name='reprintrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reprint_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reprintrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('downloaded', 'Downloaded'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='requested', max_length=20),
        ),
        migrations.AddIndex(
            model_name='reprintrequest',
            index=models.Index(fields=['card', 'status'], name='core_reprin_card_id_04bcf5_idx'),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelTable(
                    name='reprintrequest',
                    table='core_reprintrequest',
                ),
            ],
            database_operations=[],
        ),
    ]
