# Generated by Django 5.2.12 on 2026-06-27 08:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('active_clients', models.IntegerField(default=0)),
                ('active_assistants', models.IntegerField(default=0)),
                ('peak_active_users', models.IntegerField(default=0)),
                ('total_cards_created', models.IntegerField(default=0)),
                ('total_cards_approved', models.IntegerField(default=0)),
                ('batch_jobs_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Stats Snapshot',
                'verbose_name_plural': 'Stats Snapshots',
                'ordering': ['-timestamp'],
            },
        ),
    ]
