# Generated by Django 5.2.12 on 2026-07-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerLoadAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('warning', 'Warning (50+)'), ('critical', 'Critical (75+)'), ('danger', 'Danger (100+)')], max_length=16, unique=True)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('last_count', models.IntegerField(default=0, help_text='Concurrent users when the alert was last triggered')),
            ],
            options={
                'verbose_name': 'Server Load Alert',
                'verbose_name_plural': 'Server Load Alerts',
            },
        ),
    ]
