# Generated by Django 5.2.12 on 2026-07-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_add_server_load_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='statssnapshot',
            name='active_desktop_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statssnapshot',
            name='active_mobile_users',
            field=models.IntegerField(default=0),
        ),
    ]
