# Generated by Django 5.2.12 on 2026-08-12 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assistant',
        ),
    ]
