# Generated by Django 5.2.12 on 2026-08-14 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0004_alter_assistant_organisation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='The Manager or Prime Manager this assistant belongs to. Deleting the manager cascades deletion of their assistants.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_assistants', to=settings.AUTH_USER_MODEL),
        ),
    ]
